---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: true

- name: Ensure PostgreSQL is started
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create database user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: student
    password: "yourpassword"
    state: present

- name: Create database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: tasktracker
    owner: student
    state: present

- name: Configure PostgreSQL to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL

- name: Deploy pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0640"
  notify: Restart PostgreSQL
